apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: hipster-shop
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.10.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - port: 8080
    targetPort: 8080
