apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: hipster-shop
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.10.0
        ports:
        - containerPort: 50051
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - port: 50051
    targetPort: 50051
